---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8888}]
provisioner:
  name: chef_solo
  environments_path: test/environments

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
        - recipe[flasky-cookbook::default]
    attributes:
